# Generated by Django 5.0.2 on 2024-02-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_per',
            old_name='std_id',
            new_name='Sts_Usn',
        ),
    ]
