# Generated by Django 5.0.2 on 2024-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
