# Generated by Django 5.0.2 on 2024-02-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0002_rename_std_id_academic_per_sts_usn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_per',
            old_name='Sts_Usn',
            new_name='std_id',
        ),
    ]
