# Generated by Django 5.0 on 2024-03-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certi_skills',
            name='certi_s_date',
        ),
    ]
