# Generated by Django 5.0.2 on 2024-02-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0003_rename_sts_usn_academic_per_std_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_per',
            name='sem10th',
        ),
        migrations.RemoveField(
            model_name='academic_per',
            name='sem12th_diploma',
        ),
    ]
