# Generated by Django 5.0 on 2024-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0004_remove_certi_skills_certi_s_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certi_skills',
            name='certi_outcomes',
        ),
        migrations.AddField(
            model_name='certi_skills',
            name='org',
            field=models.CharField(default='aa', max_length=255),
        ),
    ]
