# Generated by Django 5.0 on 2024-03-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0005_remove_certi_skills_certi_outcomes_certi_skills_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_specification',
        ),
    ]
