# Generated by Django 5.0 on 2024-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0006_remove_projects_project_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_repo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
