# Generated by Django 5.0 on 2024-03-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0007_alter_projects_project_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_per',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr_mange.batch'),
        ),
        migrations.AddField(
            model_name='academic_per',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr_mange.branch'),
        ),
    ]
