# Generated by Django 5.0 on 2024-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_mange', '0008_academic_per_batch_academic_per_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='certi_skills',
            name='specification',
            field=models.CharField(default='aa', max_length=255),
        ),
    ]
